#!/bin/bash

# displayline (Skim)
#
# Usage: displayline [-r] [-b] [-g] [-z] LINE PDFFILE [TEXSOURCEFILE]

if [[ $# -eq 0 || "$1" == "-h" || "$1" == "-help" ]]; then
  echo "Usage: displayline [-r] [-b] [-g] [-z] LINE PDFFILE [TEXSOURCEFILE]
Options:
-r, -revert      Revert the file from disk if it was open
-b, -readingbar  Indicate the line using the reading bar
-g, -background  Do not bring Skim to the foreground
-z, -zerobased   LINE is zero-based rather than one-based"
  exit 0
fi

# get arguments
revert="false"
showing_bar=""
activate="activate"
zerobased=
while [[ "${1:0:1}" == "-" ]]; do
  if [[ "$1" == "-r" || "$1" == "-revert" ]]; then
    revert="true"
  elif [[ "$1" == "-b" || "$1" == "-readingbar" ]]; then
    showing_bar="with showing reading bar"
  elif [[ "$1" == "-g" || "$1" == "-background" ]]; then
    activate=""
  elif [[ "$1" == "-z" || "$1" == "-zerobased" ]]; then
    zerobased="1"
  fi
  shift
done
line=$1
file="$2"
shopt -s extglob
[[ $# -gt 2 ]] && src="$3" || src=""

# expand relative paths
[[ "${file:0:1}" == "/" ]] || file="${PWD}/${file}"
[[ "${src}" == "" || "${src:0:1}" == "/" ]] || src="${PWD}/${src}"

[[ "${src}" == "" ]] && from_source="" || from_source="from POSIX file \"$src\""

[[ -z ${zerobased} ]] || (( line+=1 ))

# run AppleScript
/usr/bin/osascript << EOF
  set theFile to POSIX file "$file"
  tell application "Skim"
    if $revert then
      try
        set thePath to POSIX path of (theFile as alias)
        set theDocs to get documents whose path is thePath
        if (count of theDocs) > 0 then revert theDocs
      end try
    end if
    open theFile
    tell front document to go to TeX line $line $from_source $showing_bar
    $activate
  end tell
EOF
